Repository kevinniel/MDS-B3-GIT-2324, pull requests merged in 2023-12, with the labels that each got.

#26 Groupe 3
  GitHub.md
  Java.md
  Ruby.md
  gitlab.md
  image.png
Labels: GROUPE 3

#33 Groupe 4 - Chef Yaël
  Beautiful Soup.md
  Caddy.md
  Redis.md
  Solidity.md
Labels: GROUPE 4

#32 PR Groupe 6 🎉
  Heroku.md
  Netlify.md
  SQLServer.md
  UnrealEngine
  UnrealEngine.md
Labels: GROUPE 2

#31 Groupe 1 (Flask, leaflet, Ploty, keycloak)
  Flask.md
  Leaflet.md
  Plotly.md
  keycloak.md
  leaflet.png
Labels: GROUPE 1

#35 Groupe 3
  C++.md
  Firebase.md
  Jest.md
  image-1.png
  nuxt.md
Labels: GROUPE 3

#39 Add documentations for : LUA, Ant design, seaborn and Postman
  AntDesign.md
  LUA.md
  Postman.md
  seaborn.md
Labels: GROUPE 2

#38 Groupe 5 - PR
  Azure.md
  Boostrap.md
  MapBox.md
  PostgreSQL.md
  Swift.md
  Symfony.md
  go.md
  ruby.md
Labels: GROUPE 5

#43 Groupe 5
  GCP.md
  Rust.md
  express.md
Labels: GROUPE 5

#46 Groupe 4
  API.md
  Apache.md
  Latex.md
  NGINX.md
Labels: GROUPE 4

#49 Groupe 5
  JWT.md
  yARN.md
Labels: GROUPE 5

#50 ➕ Add documents Groupe 2
  .gitignore
  MeteorJS.md
  MoDB.md
  MongoDB.md
  Polymer_JS.md
  Selenium
  Selenium.md
  ruby.md
Labels: GROUPE 2

#53 Groupe 3
  CakePHP.md
  Sylius.md
  asp.net.md
  image-2.png
  unity.md
Labels: GROUPE 3

#52 Pas une erreur cette fois ci ^^ :camera_flash: :camera_flash:
  Stripe.md
  VisualStudioCode.md
  aXIoS.md
Labels: GROUPE 5
